//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanci
    {
        public Clanci()
        {
            this.ClanciKomentari = new HashSet<ClanciKomentari>();
            this.ClanciOcjene = new HashSet<ClanciOcjene>();
            this.Pitanja = new HashSet<Pitanja>();
            this.Tagovi = new HashSet<Tagovi>();
            this.ClanciIzmjene = new HashSet<ClanciIzmjene>();
        }
    
        public int ClanakID { get; set; }
        public string Naslov { get; set; }
        public string Autori { get; set; }
        public string Tekst { get; set; }
        public string KljucneRijeci { get; set; }
        public int VrstaID { get; set; }
        public int TemaID { get; set; }
        public int KorisnikID { get; set; }
        public byte[] Dokument { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Izmjene { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumIzmjene { get; set; }
        public string DokumentType { get; set; }
        public string DokumentPath { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Teme Teme { get; set; }
        public virtual VrsteClanaka VrsteClanaka { get; set; }
        public virtual ICollection<ClanciKomentari> ClanciKomentari { get; set; }
        public virtual ICollection<ClanciOcjene> ClanciOcjene { get; set; }
        public virtual ICollection<Pitanja> Pitanja { get; set; }
        public virtual ICollection<Tagovi> Tagovi { get; set; }
        public virtual ICollection<ClanciIzmjene> ClanciIzmjene { get; set; }
    }
}
