//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FITKMSEntities : DbContext
    {
        public FITKMSEntities()
            : base("name=FITKMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aktivnosti> Aktivnosti { get; set; }
        public DbSet<Clanci> Clanci { get; set; }
        public DbSet<ClanciKomentari> ClanciKomentari { get; set; }
        public DbSet<ClanciOcjene> ClanciOcjene { get; set; }
        public DbSet<Korisnici> Korisnici { get; set; }
        public DbSet<KorisniciUloge> KorisniciUloge { get; set; }
        public DbSet<Oblasti> Oblasti { get; set; }
        public DbSet<Odgovori> Odgovori { get; set; }
        public DbSet<OdgovoriGlasovi> OdgovoriGlasovi { get; set; }
        public DbSet<Pitanja> Pitanja { get; set; }
        public DbSet<PitanjaGlasovi> PitanjaGlasovi { get; set; }
        public DbSet<Pretrage> Pretrage { get; set; }
        public DbSet<Tagovi> Tagovi { get; set; }
        public DbSet<Teme> Teme { get; set; }
        public DbSet<Uloge> Uloge { get; set; }
        public DbSet<VrsteClanaka> VrsteClanaka { get; set; }
    
        public virtual ObjectResult<VrsteClanaka> fsp_VrsteClanaka_SelectByStatus(Nullable<bool> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrsteClanaka>("fsp_VrsteClanaka_SelectByStatus", statusParameter);
        }
    
        public virtual ObjectResult<VrsteClanaka> fsp_VrsteClanaka_SelectByStatus(Nullable<bool> status, MergeOption mergeOption)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrsteClanaka>("fsp_VrsteClanaka_SelectByStatus", mergeOption, statusParameter);
        }
    }
}
