//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.Clanci = new HashSet<Clanci>();
            this.ClanciKomentari = new HashSet<ClanciKomentari>();
            this.ClanciOcjene = new HashSet<ClanciOcjene>();
            this.KorisniciUloge = new HashSet<KorisniciUloge>();
            this.Odgovori = new HashSet<Odgovori>();
            this.OdgovoriGlasovi = new HashSet<OdgovoriGlasovi>();
            this.Pitanja = new HashSet<Pitanja>();
            this.PitanjaGlasovi = new HashSet<PitanjaGlasovi>();
        }
    
        public int KorisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Mail { get; set; }
        public string Spol { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public System.DateTime DatumRegistracije { get; set; }
        public System.DateTime PosljednjaPrijava { get; set; }
        public string KorisnickoIme { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
        public byte[] Slika { get; set; }
        public bool Aktivan { get; set; }
        public Nullable<System.DateTime> DatumIzmjene { get; set; }
    
        public virtual ICollection<Clanci> Clanci { get; set; }
        public virtual ICollection<ClanciKomentari> ClanciKomentari { get; set; }
        public virtual ICollection<ClanciOcjene> ClanciOcjene { get; set; }
        public virtual ICollection<KorisniciUloge> KorisniciUloge { get; set; }
        public virtual ICollection<Odgovori> Odgovori { get; set; }
        public virtual ICollection<OdgovoriGlasovi> OdgovoriGlasovi { get; set; }
        public virtual ICollection<Pitanja> Pitanja { get; set; }
        public virtual ICollection<PitanjaGlasovi> PitanjaGlasovi { get; set; }
    }
}
