//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovori
    {
        public Odgovori()
        {
            this.OdgovoriGlasovi = new HashSet<OdgovoriGlasovi>();
        }
    
        public int OdgovorID { get; set; }
        public string Tekst { get; set; }
        public int KorisnikID { get; set; }
        public int PitanjeID { get; set; }
        public Nullable<int> Pozitivni { get; set; }
        public Nullable<int> Negativni { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<System.DateTime> DatumIzmjene { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Pitanja Pitanja { get; set; }
        public virtual ICollection<OdgovoriGlasovi> OdgovoriGlasovi { get; set; }
    }
}
