//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitanja
    {
        public Pitanja()
        {
            this.Odgovori = new HashSet<Odgovori>();
            this.PitanjaGlasovi = new HashSet<PitanjaGlasovi>();
            this.Tagovi = new HashSet<Tagovi>();
        }
    
        public int PitanjeID { get; set; }
        public string Naslov { get; set; }
        public string Tekst { get; set; }
        public int KorisnikID { get; set; }
        public Nullable<int> ClanakID { get; set; }
        public Nullable<int> TemaID { get; set; }
        public Nullable<int> Pozitivni { get; set; }
        public Nullable<int> Negativni { get; set; }
        public Nullable<int> BrojPregleda { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumIzmjene { get; set; }
    
        public virtual Clanci Clanci { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        public virtual ICollection<Odgovori> Odgovori { get; set; }
        public virtual Teme Teme { get; set; }
        public virtual ICollection<PitanjaGlasovi> PitanjaGlasovi { get; set; }
        public virtual ICollection<Tagovi> Tagovi { get; set; }
    }
}
