//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pretrage
    {
        public int PretragaID { get; set; }
        public System.DateTime Datum { get; set; }
        public int AktivnostID { get; set; }
        public string TekstPretrage { get; set; }
        public Nullable<int> ClanakID { get; set; }
        public int KorisnikID { get; set; }
    
        public virtual Aktivnosti Aktivnosti { get; set; }
    }
}
