//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITKMS_business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teme
    {
        public Teme()
        {
            this.Clanci = new HashSet<Clanci>();
            this.Pitanja = new HashSet<Pitanja>();
        }
    
        public int TemaID { get; set; }
        public string Naziv { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OblastID { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumIzmjene { get; set; }
    
        public virtual ICollection<Clanci> Clanci { get; set; }
        public virtual Oblasti Oblasti { get; set; }
        public virtual ICollection<Pitanja> Pitanja { get; set; }
    }
}
